---
project_name: py-example-project
loglevel: info
analyses:
- analysis_name: py check
  source_directory: /Users/user1/emerge/project/source
  only_permit_languages:
  - py
  only_permit_file_extensions:
  - .py
  file_scan:
  - number_of_methods
  - source_lines_of_code
  - dependency_graph
  - louvain_modularity
  - fan_in_out
  - tfidf
  export:
  - directory: /Users/user1/emerge/project/export
  - graphml
  - dot
  - json
  - tabular_file
  - tabular_console_overall
  - d3
