---
project_name: swift_example_project
loglevel: info
analyses:
- analysis_name: full swift check
  source_directory: /Users/grzegorz.lato/Private/Code/github/clean-architecture-swiftui
  only_permit_languages:
  - swift
  only_permit_file_extensions:
  - .swift
  file_scan:
  - number_of_methods
  - source_lines_of_code
  - dependency_graph
  - fan_in_out
  - louvain_modularity
  entity_scan:
  - inheritance_graph
  - dependency_graph
  - source_lines_of_code
  - number_of_methods
  - fan_in_out
  - louvain_modularity
  export:
  - directory: /Users/grzegorz.lato/temp/swift-export
  - graphml
  - dot
  - json
  - tabular_file
  - tabular_console_overall
  - d3
